# Generated by Django 5.1.4 on 2025-01-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='challenges/'),
        ),
    ]
