from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

# Import your viewsets
from apps.users.views import UserViewSet
from apps.challenges.views import ChallengeViewSet, InteractionViewSet, ChallengeResponseViewSet, TaggitTagViewSet, TaggitTaggedItemViewSet

router = DefaultRouter()
router.register(r'users', UserViewSet, basename='user')
router.register(r'challenges', ChallengeViewSet, basename='challenge')
router.register(r'challenge-responses',
                ChallengeResponseViewSet, basename='challengeresponse')
router.register(r'interactions', InteractionViewSet,
                basename='interaction')
router.register(r'tags', TaggitTagViewSet, basename='tag')
router.register(r'tagged-items', TaggitTaggedItemViewSet,
                basename='taggeditem')

urlpatterns = [
    path('admin/', admin.site.urls),

    # This line includes all the routes generated by DRF's router
    # under the /api/ path.
    path('api/', include(router.urls)),
]


urlpatterns += [
    path('api-auth/', include('rest_framework.urls')),
]

# Only for development/debug!
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
