# backend/urls.py (or myproject/urls.py)
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

# Import your viewsets
from apps.users.views import UserViewSet
from apps.challenges.views import ChallengeViewSet

router = DefaultRouter()
router.register(r'users', UserViewSet, basename='user')
router.register(r'challenges', ChallengeViewSet, basename='challenge')

urlpatterns = [
    path('admin/', admin.site.urls),

    # This line includes all the routes generated by DRF's router
    # under the /api/ path.
    path('api/', include(router.urls)),
]


urlpatterns += [
    path('api-auth/', include('rest_framework.urls')),
]
