# Generated by Django 5.1.4 on 2025-01-02 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 7, 14, 9, 14, 36206, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
