# Generated by Django 5.1.4 on 2025-01-02 15:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_alter_challenge_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 7, 15, 44, 18, 511895, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='challenges.response'),
        ),
    ]
