# Generated by Django 5.1.4 on 2025-01-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_challenge_tags_response_tags_delete_challengetag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='responses/'),
        ),
    ]
