# Generated by Django 5.1.4 on 2025-01-02 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_alter_challenge_end_time_alter_interaction_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='response',
            name='title',
            field=models.CharField(default='My Response', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 7, 16, 5, 44, 609093, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote'), ('flag', 'Flag'), ('bookmark', 'Bookmark'), ('report', 'Report')], max_length=50),
        ),
    ]
