# Generated by Django 5.1.4 on 2025-01-03 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_rename_content_response_description_response_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 8, 10, 14, 17, 668013, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
